apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: admin-kubeflow-org
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-collector
  namespace: admin-kubeflow-org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-collector
subjects:
- kind: ServiceAccount
  name: metrics-collector
  namespace: admin-kubeflow-org
